### ISSUE TITLE
check sign in definition of p and sminux

### ISSUE THREAD

**Issue by d-meiser** [d-meiser/crossover#11]

**Comment by d-meiser** [comment]
The sign convention gives the wrong sign in the commutator of q and p. There is also an issue with the normalization beeing too small by a factor of 1/sqrt(2).

But apparently this is the definition that has been used in the calculation (e.g. in the computation of the diffusion matrix elements). So perhaps we just leave things the way they are?

We should decide what to do, so I'm leaving this open for now.

**Comment by d-meiser** [comment]
@dtieri and @murrayjholland , should we just leave this unchanged? As far as I can tell David used these conventions consistently.

**Comment by dtieri** [comment]
That is fine with me.

David
