### ISSUE TITLE
pac numbers

### ISSUE THREAD

**Issue by d-meiser** [d-meiser/crossover#2]
@dtieri can you look up 3 or 4 suitable pac numbers for the paper in put them in the tex file. Thanks.

**Comment by d-meiser** [comment]
Hi @dtieri, thanks for looking up the pacs  numbers. Could you perhaps add the descriptions of the topics either in a comment in the tex file or in this thread. Thanks.

**Comment by dtieri** [comment]
42.50.Nn: Quantum optical phenomena in absorbing, amplifying, dispersive
and conducting media; cooperative phenomena in quantum optical systems

06.30.Ft: Time and frequency https://ufn.ru/en/pacs/06.30.Ft/

37.30.+i: Atoms, molecules and ions in cavities

42.50.Ct: Quantum description of interaction of light and matter; related
experiments

**Comment by d-meiser** [comment]
Thanks.
