### ISSUE TITLE
Intuitive explanation of improved stability with smaller T2

### ISSUE THREAD

**Issue by d-meiser** [d-meiser/crossover#5]

**Comment by dtieri** [comment]
Hey Dominic, Murray and I have been updating the tex file, and I cant push
the changes, we rewrote the crossover parameter section and added a few
other things. I included our .tex file if this helps

David

**Comment by d-meiser** [comment]
Hey Dave, can you try to run the following command in the crossover
directory:

git pull

After that you should be able to push. I can walk you through it via im.

Dominic

**Comment by d-meiser** [comment]
Alternatively, you can do the following:

```
git checkout -b daves-changes
git push origin daves-changes
```
